[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "python-telegram-bot>=22.5",
    "telethon>=1.41.2",
    "termcolor>=3.2.0",
]
